### ISSUE TITLE
has anyone been able to use a full-chain certificate as the SP certificate ? 

### ISSUE THREAD

**Issue by steveinatorx** [handnot2/esaml#35]
Failed load SP certfile

**Comment by samterrell** [comment]
SAML is generally a point-to-point trust system using self-signed certificates. This is one of the advantages of OpenID... The spec includes provisions for key rotation and discovery. I have never seen anything but self-signed certificates in either, but with OpenID, the signing keys can be discovered over HTTPS which uses x509 validation (so you can trust the signing key without prior knowledge).

Both of those are generally only going to get you email address validation, which in a B2C setting is more reliably achieved via emailing nonce tokens to users, which is why you most sites require you to validate your email/phone via sending you a code.

It could be interesting if you had a use case where you could trust a CA to sign a set of SAML signing certs to authenticate either an SP or IDP that you were willing to trust (rather than setting up individual trust relationships with each). Essentially each IDP in the SAML ecosystem operates as a CA in that they assert the identity of users as a normal CA asserts either domain ownership or identity of a site.
